# Install it using ansible-galaxy collection install community.mysql
# Installation of MariaDB itself and securing everything is done manually
# To ensure no leaks in database

- name: MariaDB Configuration
  hosts: database
  gather_facts: no
  vars:
    # Add another client when there's another 
    # server installed or configured here
    ip: []

  tasks:
    - name: Getting Webservers IP Addresses
      set_fact:
        ip: "{{ ip + hostvars[item]['inventory_hostname'] | regex_search('client@([0-9]+.[0-9]+.[0-9]+.[0-9]+)', '\\1') }}" 
      loop: "{{ groups['webservers'] }}"

    - name: Allow connection from user
      firewalld:
        zone: public
        rich_rule: 'rule family="ipv4" source address="{{ item }}" port protocol="tcp" port="3306" accept'
        permanent: true
        state: enabled
      loop: "{{ ip }}"
      become: yes

    - name: Reload Firewall
      become: yes
      service:
        name: firewalld
        state: reloaded

    - name: Ensure pip for python2 installed
      become: yes
      package:
        name: python-pip
        state: present

    - name: Download module for mysql module
      pip:
        name: PyMySQL==0.10.0
        state: present
        extra_args: --user

    - name: Grant access to each user 
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ user_client_password }}"
        name: "client"
        host: "{{ item }}"
        password: "{{ user_client_password }}"
        priv: 'wordpress.*:ALL'
        state: present
      loop: "{{ ip }}"