- name: Copying service file & Enabled service...
  become: yes
  template:
    src: "templates/node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
  notify: 
    - ReloadingDaemon
    - EnablingNodeExporter
  changed_when: True
  when: fresh_install_flag == True

- name: Reloading service...
  become: yes
  template:
    src: "templates/node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
  notify:
    - ReloadingDaemon
    - RestartingNodeExporter
  changed_when: True