- include_tasks: permission.yml
  when: installed_flag == False

- include_tasks: install.yml
  when: installed_flag == False

- include_tasks: mounting.yml
  when: installed_flag == True

- include_tasks: running.yml
  when: installed_flag == True