- name: Ensure mounting service running
  service:
    name: nfs-utils
    state: started
  become: yes

- name: Getting Webservers IP Addresses
  set_fact:
    ip: "{{ ip + hostvars[item]['inventory_hostname'] | regex_search('client@([0-9]+.[0-9]+.[0-9]+.[0-9]+)', '\\1') }}" 
  loop: "{{ groups['webservers'] }}"
  run_once: true

- name: Configure exports
  become: yes
  local_action:
    module: template
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  changed_when: true
  notify: reload_nfs

- name: Run the handlers first before mounting
  meta: flush_handlers

- name: Mounting wordpress
  ansible.posix.mount:
    src: 192.168.100.20:/home/master/Documents/WordPress/
    path: /home/client/WordPress/
    state: mounted
    fstype: nfs
  become: yes
