- name: Setting up nodeExporter
  hosts: webservers
  become: yes
  gather_facts: false

  tasks:
    - name: Make the directory
      file:
        path: /home/client/Node
        state: directory

    - name: Copying Node Exporter file
      copy:
        src: /media/master/Data/[Project] Blibli/monitoring/node_exporter
        dest: /home/client/Node/node_exporter
        owner: client
        group: client
        mode: '0755'

    - name: Copying configuration
      copy:
        src: /media/master/Data/[Project] Blibli/monitoring/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: '0755'
      become_method: sudo
      become_user: root

    - name: Reloading systemd system
      systemd:
        state: started
        daemon_reload: yes
        name: node_exporter.service
        enabled: yes
