- name: Haproxy config
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Applying config from template
      template:
        src: haproxy.cfg.j2
        dest: haproxy.cfg