- name: Setting up nodeExporter
  hosts: allserver
  gather_facts: false

  tasks:
    - name: Ensure directory exists
      file:
        path: /home/client/Node
        state: directory

    - name: Moving the application
      copy:
        src: /media/master/Data/[Project] Blibli/PlaybookUsed/Monitoring/NodeExporter/node_exporter
        dest: /home/client/Node/node_exporter
        owner: client
        group: client
        mode: '0755'

    - name: Copying service file
      copy:
        src: /media/master/Data/[Project] Blibli/PlaybookUsed/Monitoring/NodeExporter/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: '0755'
      become: yes

    - name: Reloading node exporter service and enable it
      systemd:
        state: started
        daemon_reload: yes
        name: node_exporter.service
        enabled: yes
      become: yes