- name: Checking Directory...
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - { path: "{{ installation_destination }}" }
    - { path: "{{ installation_destination }}/prometheus" }
    - { path: "{{ installation_destination }}/prometheus/data"}

- name: Fetching, Extracting, & Moving the file...
  unarchive:
    src: "{{ github_url }}/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "{{ installation_destination }}/prometheus"
    extra_opts: [--strip-components=1]
    remote_src: yes