- name: Automation_python3 interface
  hosts: webservers
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create WordPress directory
      file:
        path: /home/client/WordPress
        state: directory

    - name: Copy Dockerfile
      copy: 
        src: /media/master/Data/[Project] Blibli/PlaybookUsed/WordPress/Dockerfile
        dest: /home/client/Dockerfile
        owner: client
        group: docker
        mode: '0740'

    - name: Reset SSH
      meta: reset_connection

    - name: Enable docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Enable mounting service
      service:
        name: nfs-utils
        state: started
        enabled: yes
      become: yes

    - name: Install dependencies for docker module
      pip:
        name: 
          - docker
          # Things listed below docker may differ
          - six
        extra_args: --user
        state: latest

    - name: Building image from Dockerfile
      docker_image:
        name: wordpress
        path: /home/client/.
        state: present