- name: Running Docker
  hosts: webservers
  become_user: client
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Mounting
      ansible.posix.mount:
        src: 192.168.100.20:/home/master/Documents/WordPress
        path: /home/client/WordPress
        state: mounted
        fstype: nfs
      become: yes

    - name: Making Containers
      docker_container:
        name: "{{ item.name }}"
        image: wordpress
        recreate: yes
        volumes: /home/client/WordPress:/var/www/localhost/htdocs
        published_ports: "{{ item.port }}"
        state: started
        detach: yes
      loop:
        - { name: 'WordPress1', port: 81:80 }
        - { name: 'WordPress2', port: 82:80 }
        - { name: 'WordPress3', port: 83:80 }
