- name: Running Docker
  hosts: webservers
  become_user: client
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
   - name: Mounting
     ansible.posix.mount:
       src: 192.168.100.20:/home/master/Documents/WordPress
       path: /home/client/WordPress
       state: mounted
       fstype: nfs
     become: yes
     become_user: root
     become_method: sudo

   - name: Make 1st Container
     docker_container:
       name: WordPress1
       image: wordpress
       recreate: yes
       volumes: /home/client/WordPress:/var/www/localhost/htdocs
       published_ports: 81:80
       state: started
       detach: yes

   - name: Make 2nd Container
     docker_container:
       name: WordPress2
       image: wordpress
       recreate: yes
       volumes: /home/client/WordPress/:/var/www/localhost/htdocs
       published_ports: 82:80
       state: started
       detach: yes

   - name: Make 3rd Container
     docker_container:
       name: WordPress3
       image: wordpress
       recreate: yes
       volumes: /home/client/WordPress/:/var/www/localhost/htdocs
       published_ports: 83:80
       state: started
       detach: yes
